### ISSUE TITLE
UnicodeDecodeError: illegal multibyte sequence

### ISSUE THREAD

**Issue by mgdreamingstar** [neoclide/coc-python#169]
## versions

vim version: NVIM v0.4.3
node version: v10.16.3
coc.nvim version: 0.0.77
term: vtpcon
platform: win32

## Output channel: snippets

[Info 6:49:10 PM] Using ultisnips directories: UltiSnips C:\Users\GRC\AppData\Local\coc\ultisnips
[Info 6:49:12 PM] Using ultisnips python command: pyx
Error on execute python script:
request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 5 (python3-script-host):
error caught in request handler 'python_execute_file ['C:\\Users\\GRC\\AppData\\Local\\Temp\\coc.nvim-96752\\coc-ultisnips-L5MDSuyzUw.py', 106, 106]':
Traceback (most recent call last):
  File "D:\Anaconda\envs\new3\lib\site-packages\pynvim\plugin\script_host.py", line 106, in python_execute_file
    script = compile(f.read(), file_path, 'exec')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 18226: illegal multibyte sequence
## Output channel: Python

Starting Microsoft Python language server.

## Describe the bug

Can't start python-interpreter.

**Comment by chemzqm** [comment]
Should be problem of your python.

**Comment by hyhugh** [comment]
> Should be problem of your python or pynvim.

Hi I just tested this on windows, I can reproduce this problem and it seems it's actually related to coc-snippets


```
vim version: NVIM v0.4.3
node version: v14.5.0
coc.nvim version: 0.0.78-c9246e45a1
coc.nvim directory: C:\Users\hyhugh\HyVim\bundle\coc.nvim
term: vtpcon
platform: win32

## Output channel: snippets

[Info 10:49:08 pm] Using ultisnips directories: UltiSnips C:\Users\hyhugh/HyVim/ultisnips
[Info 10:49:08 pm] Using ultisnips python command: pyx
Error on execute python script:
request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
error caught in request handler 'python_execute_file ['C:\\Users\\hyhugh\\AppData\\Local\\Temp\\coc.nvim-11504\\coc-ultisnips-THnuHZHLwK.py', 1, 1]':
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pynvim\plugin\script_host.py", line 106, in python_execute_file
    script = compile(f.read(), file_path, 'exec')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 18433: illegal multibyte sequence
```
