### ISSUE TITLE
Jedi 0.17.0 seems break coc-python

### ISSUE THREAD

**Issue by cmcclellen** [neoclide/coc-python#175]
Looks like Jedi 0.17.0 was released yesterday and code completion in coc.nvim/coc-python is broken.  Whenever it tries to complete something I get:
```
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "completion.py", line 624, in watch
    response = self._process_request(rq)
  File "completion.py", line 571, in _process_request
    script = jedi.Script(
  File "XXXXXX/venv/lib/python3.8/site-packages/jedi/api/__init__.py", line 133, in __init__
    project._sys_path = sys_path
AttributeError: 'NoneType' object has no attribute '_sys_path'
```

The above file path in the exception was edited for brevity.

Moving back to jedi 0.16.0 makes things work again.

**Comment by naiveai** [comment]
It is unclear whether this is an issue with jedi itself or not - it seems the code in jedi does not take into account the fact that project could be `None` in this case, or perhaps it doesn not do that becuase that's now how its clients are supposed to behave.

**Comment by languitar** [comment]
Any way to downgrade things to a working version? Pretty annoying to work with the constant exceptions.

**Comment by RaphGL** [comment]
> Any way to downgrade things to a working version? Pretty annoying to work with the constant exceptions.

yes! just run:
sudo pip  install --upgrade jedi==0.16.0

**Comment by ljvmiranda921** [comment]
The command above works, `sudo` and `--upgrade` may not be required. The following worked for me:

```
pip install jedi==0.16.0
```

**Comment by z0w13** [comment]
> 
> 
> It is unclear whether this is an issue with jedi itself or not - it seems the code in jedi does not take into account the fact that project could be `None` in this case, or perhaps it does not do that becuase that's not how its clients are supposed to behave.

Jedi's behaviour in 0.17 changed, the `sys_path` argument to `Script` is deprecated, and they now expect you to supply a project

https://github.com/davidhalter/jedi/blob/master/jedi/api/__init__.py#L132

**Comment by Rizhiy** [comment]
Would be nice to continue supporting Jedi, MPLS doesn't work on installed packages, which is annoying.

**Comment by phootip** [comment]
I almost cried trying to fix this error, uninstalled anaconda, reinstalled python, rollbacked to python 3.7 instead of 3.8. Thank you, and it would be nice to fix this or add this to doc

**Comment by haoqixu** [comment]
This is a bug of Jedi 0.17.0. The patch has been merged.davidhalter/jedi/pull/1549

**Comment by haoqixu** [comment]
coc-python 1.2.12 has switched to the new api introduced by Jedi 0.17.0. Upgrading coc-python to 1.2.12 works well for me.
