### ISSUE TITLE
Way to disable MLPS linter, python.analysis?

### ISSUE THREAD

**Issue by matteha** [neoclide/coc-python#18]
When MLPS is turned on (jedi enabled = False) and the linters are off, it still seems to 'lint' through the python.analysis thing of MLPS (I think it is). Please see below (the messages of the 'linter' overlap with the code below). Is there a way to turn that off?

<img width="608" alt="Screen Shot 2019-03-28 at 10 54 27 AM" src="https://user-images.githubusercontent.com/36545991/55167825-0da62c00-5148-11e9-81b5-66f0c30365db.png">

I tried the following in coc-settings but it doesn't seem to help:

"python.jediEnabled": false,   
  "python.analysis.logLevel": "Fatal",
  "python.analysis.errors": ["undefined-variable"],
  "python.analysis.errors": ["undefined-variable"],
  "python.analysis.information": ["undefined-variable"],
  "python.linting.enabled": false,

**Comment by chemzqm** [comment]
Use `"python.analysis.disabled"`

**Comment by matteha** [comment]
Thanks!

**Comment by matteha** [comment]
Once I add "python.analysis.disabled" to coc-settings.json, the LS throws this error (from CocInfo) and doesn't function anymore:

[Info  - 11:22:21 AM] Configuration search paths:
[Info  - 11:23:01 AM] Microsoft Python Language Server version 0.2.31.0
[Info  - 11:23:01 AM] Initializing for /usr/local/opt/python/bin/python3.6

Unhandled Exception: 
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Python.LanguageServer.Diagnostics.DiagnosticsService.PublishDiagnostics()
   at Microsoft.Python.LanguageServer.Diagnostics.DiagnosticsService.OnIdle(Object sender, EventArgs e)
   at Microsoft.Python.Core.Services.IdleTimeService.OnTimer(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
[Info  - 11:23:51 AM] Connection to server got closed. Server will restart.
[Error  - 11:23:51 AM] Request textDocument/completion failed.
Error: Connection got disposed.

**Comment by chemzqm** [comment]
"python.analysis.disabled" only accept set of strings, install coc-json and use coc-settings.json to have validation.

**Comment by matteha** [comment]
I see, thanks!
