### ISSUE TITLE
LookupError: no codec search functions registered: can't find encoding

### ISSUE THREAD

**Issue by Gee19** [neoclide/coc-python#211]
Seeing this after migrating to Ubuntu 18, any ideas?

```
## versions

vim version: NVIM v0.5.0-503-g9816173fb
node version: v14.2.0
coc.nvim version: 0.0.78
term: xterm-kitty
platform: linux

## Output channel: Python
Starting Microsoft Python language server.
[Info  - 3:19:34 a.m.] Analysis cache path: /home/jordan/.cache/Microsoft/Python Language Server
[Info  - 3:19:34 a.m.] Microsoft Python Language Server version 0.5.50.0
[Info  - 3:19:34 a.m.] Workspace root: /home/jordan/dev/reponame
[Info  - 3:19:34 a.m.] GetCurrentSearchPaths /home/jordan/Envs/reponame/bin/python
Traceback (most recent call last):
  File "/home/jordan/.config/coc/extensions/coc-python-data/languageServer.0.5.50/get_search_paths.py", line 31, in <module>
    import site
  File "/home/jordan/Envs/reponame/lib/python2.7/site.py", line 165, in <module>
    main()
  File "/home/jordan/Envs/reponame/lib/python2.7/site.py", line 19, in main
    load_host_site()
  File "/home/jordan/Envs/reponame/lib/python2.7/site.py", line 54, in load_host_site
    full_path = os.path.abspath(os.path.join(here, path.encode("utf-8")))
LookupError: no codec search functions registered: can't find encoding
```

**Comment by chemzqm** [comment]
Should be problem of your python without utf-8 support.

**Comment by Gee19** [comment]
Seems to be system python2 causing issues, oh well.
