### ISSUE TITLE
Jedi error while using the extension

### ISSUE THREAD

**Issue by F4zii** [neoclide/coc-python#242]
While using the extension and writing my code, this error pops up - 
![image](https://user-images.githubusercontent.com/44242259/86216002-07420380-bb86-11ea-8443-39532c020751.png)
```py
[coc.nvim]: TypeError: item.dispose is not a function
    at Object.disposeAll (/home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/util/index.js:47:18)
    at Object.deactivate (/home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/extensions.js:811:24)
    at Extensions.deactivate (/home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/extensions.js:505:36)
    at Object.ExtensionList.addAction.persist [as execute] (/home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/list/source/extensions.js:26:44)
    at /home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/list/manager.js:754:76
    at Array.map (<anonymous>)
    at ListManager.doItemAction (/home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/list/manager.js:754:41)
    at ListManager.doAction (/home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/list/manager.js:209:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/iddos/.dotfiles/config/nvim/plugged/coc.nvim/lib/list/mappings.js:32:13
```

**Comment by dylanirlbeck** [comment]
Getting this same issue.

**Comment by hakanohi** [comment]
I got the same error: 
`[coc.nvim] Jedi error: Cannot call write after a stream was destroyed`
but it got fixed once I pip installed jedi for the interpreter I was working with.
