### ISSUE TITLE
coc-python has error on startup

### ISSUE THREAD

**Issue by dpriedel** [neoclide/coc-python#3]
I just did an update of coc.nvim and and a CocInstall of coc-python.

I am running vim 8.1

When I open a python file I get the following error:

> 2019-03-26T19:39:33.101 INFO (pid:12031) [plugin] - coc initialized with node: v8.9.0
2019-03-26T19:41:43.539 INFO (pid:12143) [services] - registed service "languageserver.ccls"
2019-03-26T19:41:43.625 ERROR (pid:12143) [util-factoroy] - TypeError: Reflect.hasOwnMetadata is not a function
    at /home/dpriedel/.config/coc/extensions/node_modules/inversify/lib/annotation/injectable.js:7:21
    at Object.__decorate (/home/dpriedel/.config/coc/extensions/node_modules/tslib/tslib.js:90:99)
    at Object.<anonymous> (/home/dpriedel/.config/coc/extensions/node_modules/coc-python/lib/common/utils/random.js:25:18)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:67:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
2019-03-26T19:41:43.652 INFO (pid:12143) [plugin] - coc initialized with node: v8.9.0

Thanks

**Comment by oblitum** [comment]
Did you update coc.nvim  to master as required by README? I've seen similar errors when it's not tip of master.

**Comment by dpriedel** [comment]
yes

[dpriedel@manjaro coc.nvim]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by matteha** [comment]
This fixed it for me (thanks to the suggestion of the developer):

Use Plug 'neoclide/coc.nvim', { 'do': 'yarn install --frozen-lockfile'} as Plug command of vim-plug and reinstall coc.nvim

**Comment by oblitum** [comment]
> EDIT: I now did a call coc#util#build() after the update and that error message has gone away.

So I guess you may close this one.

**Comment by dpriedel** [comment]
Calling coc#util#build() seems to get the extension going so I'm all set regarding that
