### ISSUE TITLE
Why did this happen whenever I opened a python file

### ISSUE THREAD

**Issue by guzy0324** [neoclide/coc-python#311]
[coc.nvim] error: Uncaught exception: Error: spawn pyenv ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
[coc.nvim] error: Uncaught exception: Error: spawn python3.7 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Uncaught exception: Error: spawn python3.6 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Uncaught exception: Error: spawn C:\Python27\python.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by asammad48** [comment]
If you use python3 on linux just replace python with python3 in spawn process
