### ISSUE TITLE
Prospector with empty output

### ISSUE THREAD

**Issue by FelipeMarcelino** [neoclide/coc-python#41]
I have a problem using coc-python with prospector. 
I don't have any output with prospector when a use a specific configuration:

{
    "diagnostic.refreshOnInsertMode": true,
    "suggest.enablePreview": false,
    "coc.preferences.formatOnSaveFiletypes": ["python"],
    "diagnostic.joinMessageLines":true,
    "diagnostic.checkCurrentLine":true,
    "diagnostic.warningSign":"",
    "diagnostic.errorSign": "",
    "diagnostic.infoSign": "",
    "diagnostic.hintSign": "",
    "diagnostic.displayByAle": false,
    "python.linting.enabled": true,
    "python.linting.lintOnSave": true,
    "python.jediEnabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.prospectorEnabled": true,
    "python.linting.prospectorArgs": ["--profile --my_own_profile","-D"],
    "python.linting.pydocstyleEnabled": true,
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": ["--line-length 119"],
    "python.linting.banditEnabled": true,
    "list.source.tags.command": "ctags -R ."
}

I already try put "python.linting.prospectorArgs": ["--profile","my_own_profile","-D"], but I think that two syntax don't have difference between. 

python.output:

Starting Jedi Python language engine.
##########Linting Output - pydocstyle##########
/home/felipemarcelino/documents/main/fun_lo.py:1 at module level:
        D100: Missing docstring in public module
/home/felipemarcelino/documents/main/fun_lo.py:1 in public function `teste`:
        D103: Missing docstring in public function
/home/felipemarcelino/documents/main/fun_lo.py:5 in public function `sfd`:
        D103: Missing docstring in public function
/home/felipemarcelino/documents/main/fun_lo.py:9 in public class `class_b`:
        D101: Missing docstring in public class
##########Linting Output - bandit##########
##########Linting Output - prospector##########
##########Linting Output - prospector##########
##########Linting Output - pydocstyle##########
/home/felipemarcelino/documents/main/fun_lo.py:1 at module level:
        D100: Missing docstring in public module
/home/felipemarcelino/documents/main/fun_lo.py:1 in public function `teste`:
        D103: Missing docstring in public function
/home/felipemarcelino/documents/main/fun_lo.py:5 in public function `sfd`:
        D103: Missing docstring in public function
/home/felipemarcelino/documents/main/fun_lo.py:9 in public class `class_b`:
        D101: Missing docstring in public class
##########Linting Output - bandit##########
##########Linting Output - prospector##########
##########Linting Output - prospector##########

**Comment by chemzqm** [comment]
Looks like it failed to load your profile.

**Comment by chemzqm** [comment]
When using custom args, coc-python could be failed with parse the result.

**Comment by FelipeMarcelino** [comment]
I am trying to use the prospector again. But, it seems that coc-python yet has the problem of parse prospector output. 

2019-12-26T10:29:52.266 ERROR (pid:65595) [extension-coc-python] - Python Extension: Failed to parse Prospector output SyntaxError:
~                                                               │      ↪ Unexpected end of JSON input¬
~                                                               │    4     at JSON.parse (<anonymous>)¬
~                                                               │    5     at Prospector.parseMessages (/home/felipemarcelino/.config/coc/extensions/node_modules/coc-python/lib/index.js:122544:31)¬
~                                                               │    6     at Prospector.run (/home/felipemarcelino/.config/coc/extensions/node_modules/coc-python/lib/index.js:122174:31)¬
~                                                               │    7     at processTicksAndRejections (internal/process/task_queues.js:97:5)¬
~                                                               │    8     at async LintingEngine.lintDocument (/home/felipemarcelino/.config/coc/extensions/node_modules/coc-python/lib/index.js:122934:26)¬
~                                                               │    9 2019-12-26T10:29:52.647 INFO (pid:65595) [extension-coc-python] - Python Extension: Changes in python settings detected in analysis options,
~                                                               │      ↪ Class name = LanguageServerAnalysisOptions, , Return Value: undefined¬
~                                                               │   10 2019-12-26T10:29:55.987 INFO (pid:65595) [extension-coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /home/
~                                                               │      ↪ felipemarcelino/documents¬
