### ISSUE TITLE
Error when writing buffer to disk

### ISSUE THREAD

**Issue by Guzzii** [neoclide/coc-python#43]
When saving a buffer to disk, it throws the following error in `CocInfo`. It only seems to happen with python files. Latest cog-python is installed. Any clue?
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.15.3
coc.nvim version: 0.0.67
term: iTerm.app
platform: darwin

## Error messagesUncaught exception: TypeError: Cannot read property 'remove' of undefined
    at Object.dispose (/Users/me/.config/coc/extensions/node_modules/vscode-jsonrpc/lib/events.js:99:41)
    at disposables.forEach.disposable (/Users/me/.config/coc/extensions/node_modules/coc-python/lib/common/process/proc.js:131:58)
    at Array.forEach (<anonymous>)
    at ChildProcess.proc.once (/Users/me/.config/coc/extensions/node_modules/coc-python/lib/common/process/proc.js:131:25)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

## Output channel: Python
Starting Jedi Python language engine.
##########Linting Output - pylint##########
************* Module capacity_main
408,0,refactor,too-many-branches:Too many branches (23/12)
408,0,refactor,too-many-statements:Too many statements (125/50)

------------------------------------------------------------------
Your code has been rated at 9.93/10 (previous run: 9.93/10, +0.00)
```

### Minimal Init.vim
```
set shell=bash

filetype off

call plug#begin('~/.local/share/nvim/plugged')

Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}

call plug#end()

" We have to turn this stuff back on if we want all of our features.
filetype plugin indent on " Filetype auto-detection
syntax on " Syntax highlighting

let g:python3_host_prog = expand('~/anaconda3/bin/python')
" let g:loaded_python_provider = 1 " disable python2 support
let g:python_host_prog = expand('~/anaconda3/envs/staffing/bin/python')
```

### check health from Neovim
```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Build javascript found
  - OK: Service started

```

**Comment by VDeamoV** [comment]
I have the same issue, too. When typing `:w` the error will show up.
```bash
[coc.nvim] error: Uncaught exception: TypeError: Cannot read property 'remove' of undefined
    at Object.dispose (/Users/deamov/.config/coc/extensions/node_modules/vscode-jsonrpc/lib/events.js:99:41)
    at /Users/deamov/.config/coc/extensions/node_modules/coc-python/lib/common/process/proc.js:131:58
    at Array.forEach (<anonymous>)
    at ChildProcess.<anonymous> (/Users/deamov/.config/coc/extensions/node_modules/coc-python/lib/common/process/proc.
js:131:25)
    at Object.onceWrapper (events.js:284:20)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Socket.<anonymous> (internal/child_process.js:405:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12)
```

**Comment by chemzqm** [comment]
Happens when dispose called twice.

**Comment by VDeamoV** [comment]
So how do we solve this problem?

**Comment by chemzqm** [comment]
Avoid dispose twice.
