### ISSUE TITLE
Neomake error

### ISSUE THREAD

**Issue by vperilla** [neoclide/coc-python#46]
:NeomakeInfo show me this error.
[coc.nvim] error: Uncaught exception: TypeError: Cannot read property 'remove' of undefined
    at Object.dispose (/home/perilla/.config/coc/extensions/node_modules/vscode-jsonrpc/lib/events.js:99:41)
    at disposables.forEach.disposable (/home/perilla/.config/coc/extensions/node_modules/coc-python/lib/common/process/proc.js:131:58)
    at Array.forEach (<anonymous>)
    at ChildProcess.proc.once (/home/perilla/.config/coc/extensions/node_modules/coc-python/lib/common/process/proc.js:131:25)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)

This error seems to be related with virtualtext option, because when I have errors on my
python file, I have virtualtext for each error when cursor is over the error, but when I fix
my error, virtualtext is not removed.

Console session recorded:
[https://asciinema.org/a/PKcu5yDTSBkheCtBN2SM81ntE](https://asciinema.org/a/PKcu5yDTSBkheCtBN2SM81ntE)
[](https://asciinema.org/a/PKcu5yDTSBkheCtBN2SM81ntE)

**Comment by chemzqm** [comment]
Fixed, try 1.1.9
