### ISSUE TITLE
Error loading the extension

### ISSUE THREAD

**Issue by hovnatan** [neoclide/coc-python#56]
Here is `CocOpenLog`:

```
2019-07-05T12:14:18.604 ERROR (pid:15944) [extensions] - /home/hovnatan/.config/coc/extensions/node_modules/coc-python/lib/index.js:16565
module.exports={170:{"value":"00AA","name":"FEMININE ORDINAL INDICATOR","category":"Lo","class":"0","bidirectional_category":"L","mapping":"<super> 0061","decimal_digit_value":"","digit_value":"","numeric_value":"","mirrored":"N","unicode_name":"","comment":"","uppercase_mapping":"","lowercase_mapping":"","titlecase_mapping":"","symbol":"\xAA"},186:{"value":"00BA","name":"MASCULINE ORDINAL INDICATOR","category":"Lo","class":"0","bidirectional_category":"L","mapping":"<super> 006F","decimal_digit_value":"","digit_value":"","numeric_value":"","mirrored":"N","unicode_name":"","comment":"","uppercase_mapping":"","lowercase_mapping":"","titlecase_mapping":"","symbol":"\xBA"},443:{"value":"01BB","name":"LATIN LETTER TWO WITH STROKE","category":"Lo","class":"0","bidirectional_category":"L","mapping":"","decimal_digit_value":"","digit_value":"","numeric_value":"","mirrored":"N","unicode_name":"LATIN LETTER TWO BAR","comment":"","upperc

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInContext (vm.js:297:10)
    at Module._compile (/home/hovnatan/.local/share/nvim/site/plugged/coc.nvim/build/index.js:60645:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at Object.sandboxRequire [as require] (/home/hovnatan/.local/share/nvim/site/plugged/coc.nvim/build/index.js:60676:46)
    at Object.createExtension (/home/hovnatan/.local/share/nvim/site/plugged/coc.nvim/build/index.js:60708:35)

```

**Comment by chemzqm** [comment]
Need `:CocInfo`

**Comment by hovnatan** [comment]
```
vim version: NVIM v0.4.0-1218-g84c1d3aed
node version: v11.15.0
coc.nvim version: 0.0.72-4aee0cab77
term: tmux-256color
platform: linux

## Messages
".config/i3/i3_custom_ipc_server.py" 274L, 9233C
[coc.nvim] Error on load extension coc-python from /home/hovnatan/.config/coc/extensions/node_modules/coc-python/lib/index.js: SyntaxError: Invalid or unexpected token
## Output channel: prettier


## Output channel: highlight

[Info  - 12:25:19 PM] Highlight server running in node v11.15.0

```

**Comment by hovnatan** [comment]
After I deleted `~/.config/coc` and `CocUpdate` it run.
