### ISSUE TITLE
Opening files renders errors

### ISSUE THREAD

**Issue by matteha** [neoclide/coc-python#6]
When opening files from Nerdtree, it gives these kind of errors in CocOpenLog, not sure whether it has to do with tabs/buffers and whether these need to be refreshed? When I open a file with :ex, I dont get these errors.

[Error  - 9:35:39 PM] Unable to find document file:///Users/admin/Dropbox/FinalCrawUbu/website/github/progSpyder/00000000_stface_rec.py
[Error  - 9:35:40 PM] Unable to find document file:///Users/admin/Dropbox/FinalCrawUbu/website/github/progSpyder/00000000_stface_rec.py
[Error  - 9:37:21 PM] Request textDocument/completion failed.
  Message: name
  Code: -32000 
   at Microsoft.Python.Analysis.Values.VariableCollection.DeclareVariable(String name, IMember value, VariableSource source, LocationInfo location)
   at Microsoft.Python.Analysis.Analyzer.Evaluation.ExpressionEval.DeclareVariable(String name, IMember value, VariableSource source, LocationInfo location, Boolean overwrite)
   at Microsoft.Python.Analysis.Analyzer.Handlers.ImportHandler.HandleImport(ModuleName moduleImportExpression, NameExpression asNameExpression, Boolean forceAbsolute)
   at Microsoft.Python.Analysis.Analyzer.Handlers.ImportHandler.HandleImport(ImportStatement node)
   at Microsoft.Python.Parsing.Ast.ImportStatement.Walk(PythonWalker walker)
   at Microsoft.Python.Parsing.Ast.SuiteStatement.Walk(PythonWalker walker)
   at Microsoft.Python.Parsing.Ast.PythonAst.Walk(PythonWalker walker)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.AnalyzeEntry(PythonAnalyzerEntry entry, IPythonModule module, PythonAst ast, Int32 version, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.Analyze(IDependencyChainNode`1 node, IDependencyChainWalker`2 walker, Stopwatch stopWatch, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzerEntry.<>c.<GetAnalysisAsync>b__23_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.GetAnalysisAsync(PythonAnalyzerEntry entry, CancellationToken timeoutCt, CancellationToken cancellationToken)
   at Microsoft.Python.Analysis.Analyzer.PythonAnalyzer.GetAnalysisAsync(IPythonModule module, Int32 waitTime, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.Server.Completion(CompletionParams params, CancellationToken cancellationToken)
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Completion(JToken token, CancellationToken cancellationToken)
[Error  - 9:37:49 PM] Unable to find document file:///Users/admin/Dropbox/FinalCrawUbu/website/github/progSpyder/00000000_stface_rec.py

**Comment by matteha** [comment]
Actually it also does it outside of NerdTree, not sure what the problem is here, even if I open the files with ex:

**Comment by chemzqm** [comment]
It doesn't work with unsaved file for now.

**Comment by mihaelartz** [comment]
@chemzqm I saved the file and I opened it again and same problem.

// File main.py exists on my working directory
nvim main.py // start typing i get a error
nvim // open file with nerdtree i get a error...

**Comment by mihaelartz** [comment]
@chemzqm i opened random python project and opened random file and start typing something and get a lots, lots of errors, but sometimes i get a completions

![2019-03-27-160644_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/55087487-7b9c1600-50aa-11e9-8a5a-565d7ed09503.png)

**Comment by chemzqm** [comment]
MPLS doesn't work with filename starts with number, same as #10.
Multiple workspaceFolder not supported yet, so it won't work when you open file outside current project root.
