### ISSUE TITLE
Extension fails to install on latest coc.nvim

### ISSUE THREAD

**Issue by ebkalderon** [neoclide/coc-python#7]
## Environment

* `NVIM v0.3.4`
* macOS Mojave 10.14.4 (18E226)
* **Node.js version in $PATH:** v11.11.0
* **Commit (coc.nvim):** 99789bb016cefd3730535ed7a211c600b4cc8772
* **Branch:** master

## Description

I'm running into an issue where the `coc-python` extension fails to install with the following statusline error:

```
[coc.nvim] Error loading extension from /Users/eyalkalderon/.config/coc/extensions/node_modules/coc-python/lib/index.js: Reflect.hasOwnMetadata is not a function
```

I've already removed the `'tag': '*'` from the relevant `Plug` command in my `init.vim` and have upgraded my `coc.nvim` to the latest master, as suggested [here](https://github.com/neoclide/coc.nvim/issues/359#issuecomment-476884631). Any idea what could be going wrong?

**Comment by ebkalderon** [comment]
Update: it seems that a different version of Node.js is being selected than I expected, according to the contents of `:CocOpenLog` shown below:

```
2019-03-27T14:26:17.829 INFO (pid:35920) [services] - registed service "languageserver.bash"
2019-03-27T14:26:17.830 INFO (pid:35920) [services] - registed service "languageserver.dockerfile"
2019-03-27T14:26:17.831 INFO (pid:35920) [services] - registed service "languageserver.gluon"
2019-03-27T14:26:17.986 ERROR (pid:35920) [util-factoroy] - TypeError: Reflect.hasOwnMetadata is not a function
    at /Users/eyalkalderon/.config/coc/extensions/node_modules/inversify/lib/annotation/injectable.js:7:21
    at Object.__decorate (/Users/eyalkalderon/.config/coc/extensions/node_modules/tslib/tslib.js:90:99)
    at Object.<anonymous> (/Users/eyalkalderon/.config/coc/extensions/node_modules/coc-python/lib/common/utils/random.js:25:18)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:67:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
2019-03-27T14:26:18.067 INFO (pid:35920) [services] - registed service "eslint"
2019-03-27T14:26:18.071 INFO (pid:35920) [plugin] - coc initialized with node: v8.9.0
2019-03-27T14:26:21.174 ERROR (pid:35920) [util-factoroy] - TypeError: Reflect.hasOwnMetadata is not a function
    at /Users/eyalkalderon/.config/coc/extensions/node_modules/inversify/lib/annotation/injectable.js:7:21
    at Object.__decorate (/Users/eyalkalderon/.config/coc/extensions/node_modules/tslib/tslib.js:90:99)
    at Object.<anonymous> (/Users/eyalkalderon/.config/coc/extensions/node_modules/coc-python/lib/common/utils/random.js:25:18)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:67:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
```

**Comment by ebkalderon** [comment]
[This StackOverflow post](https://stackoverflow.com/a/37535207) suggests that this type error with Inversify can be fixed by installing the `reflect-metadata` package. I will try entering the `.config/coc/extensions/node_modules`, attempt to install the package using `yarn`, and see if it works.

**Comment by ebkalderon** [comment]
Unfortunately, it didn't work. I still receive the same error:

```
2019-03-27T14:31:47.806 ERROR (pid:36138) [util-factoroy] - TypeError: Reflect.hasOwnMetadata is not a function
    at /Users/eyalkalderon/.config/coc/extensions/node_modules/inversify/lib/annotation/injectable.js:7:21
    at Object.__decorate (/Users/eyalkalderon/.config/coc/extensions/node_modules/tslib/tslib.js:90:99)
    at Object.<anonymous> (/Users/eyalkalderon/.config/coc/extensions/node_modules/coc-python/lib/common/utils/random.js:25:18)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:67:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
2019-03-27T14:31:47.953 INFO (pid:36138) [services] - registed service "eslint"
2019-03-27T14:31:47.958 INFO (pid:36138) [plugin] - coc initialized with node: v8.9.0
2019-03-27T14:31:52.277 ERROR (pid:36138) [util-factoroy] - TypeError: Reflect.hasOwnMetadata is not a function
    at /Users/eyalkalderon/.config/coc/extensions/node_modules/inversify/lib/annotation/injectable.js:7:21
    at Object.__decorate (/Users/eyalkalderon/.config/coc/extensions/node_modules/tslib/tslib.js:90:99)
    at Object.<anonymous> (/Users/eyalkalderon/.config/coc/extensions/node_modules/coc-python/lib/common/utils/random.js:25:18)
    at Module._compile (/snapshot/coc.nvim/lib/util/factory.js:67:32)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
```

In fact, I'm now seeing another error in the statusline that wasn't there before:

```
[coc.nvim] engine coc & vscode not found in /Users/eyalkalderon/.config/coc/extensions/node_modules/reflect-metadata/package.json
```

I think I am going to completely uninstall and reinstall `coc.nvim`.

**Comment by ebkalderon** [comment]
Okay, I suspect I know what is happening. I am using the [Nix package manager](https://nixos.org/nix/) to manage my toolchains on macOS, including `yarn`. According to https://github.com/NixOS/nixpkgs/issues/53820, it appears that the package provided for `yarn` in Nixpkgs is pinned to Node.js 8, instead of using whatever Node version is present in the environment.

To confirm whether this is really the problem, I will completely uninstall `coc.nvim` and then run:

```
nix-shell -p '(yarn.override { nodejs = nodejs-11_x; })' -p other-coc.nvim-system-deps-here
```

Once the environment is loaded up, I will attempt to reinstall `coc.nvim` and `coc-python` and see if that fixes the issue.

**Comment by ebkalderon** [comment]
Well, it doesn't appear to have fixed the problem. It resulted in no change, even after completely removing the `~/.config/coc` directory and the `plugged/coc.nvim` directory and reinstalling. Looking into the `coc.nvim` source code, it appears that the `package.json` specifies the following targets anyway:

```
"targets": [
  "node8-linux-x64",
  "node8-macos-x64",
  "node8-win-x64"
]
```

So I think the Node.js version discrepancy here is a red herring, because `yarn` installed via `nix-env` is already pinned to Node 8 anyway. Not really sure how to proceed from here. @chemzqm, do you have any ideas?

**Comment by ebkalderon** [comment]
Hmm, I noticed that when I run `:CocInstall coc-python`, there is a warning message by `yarn` that actually looks relevant because the type error is occurring in the `inversify` package:

```
warning: coc-python > inversify@4.14.0: Re-Released as 5.0.1
```

Can anyone reproduce?

**Comment by chemzqm** [comment]
(/snapshot/coc.nvim/lib/util/factory.js:67:32)

it means you're using binary release, `call coc#util#build()` to fix it.

**Comment by robjuffermans** [comment]
Hi, I've got the same issue. Using nvm.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-use-cocnvim-from-master-branch

Checkout `:h g:coc_node_path` if you're using nvm.

**Comment by ebkalderon** [comment]
@chemzqm Awesome, `call coc#util#build()` fixes the problem! Thank you. I'm assuming the binary release will be fixed as well on a later date?
