### ISSUE TITLE
Error output from python: Starting client failed:

### ISSUE THREAD

**Issue by the1900** [neoclide/coc-python#8]
Thank you for share this wonderful program :)

I moved from coc and coc-pyls. 
I reinstalled coc too! but It occur error. I have no idea what's wrong. Please help!

Here is my env
- OS: ubuntu x64 18.x.x LTS
- Node version: 10.15.3 (installed by NVM)
- Yarn version: 1.15.2
- vim-plug `Plug 'neoclide/coc.nvim', { 'do': 'yarn install --frozen-lockfile'}`
- output of `CocList extensions`: 
``` bash
  1 + coc-json 1.0.12 ~/.config/coc/extensions/node_modules/coc-json
  2 + coc-python 1.0.4 ~/.config/coc/extensions/node_modules/coc-python
  3 + coc-vetur 1.1.0 ~/.config/coc/extensions/node_modules/coc-vetur
```

And this is screen shot
![coc-python 제보](https://user-images.githubusercontent.com/10105141/55056633-f9abed00-50a9-11e9-8d9f-39c946d98b81.png)

Here is outpt of `:CocOpenLog`
```
705 2019-03-27T15:58:33.392 INFO (pid:15097) [extension-coc-python] - Python Extension: Interpreters returned by WorkspaceVirtualEnvService are of count 0
706 2019-03-27T15:58:33.393 INFO (pid:15097) [extension-coc-python] - Python Extension: Get language server folder name, Class name = LanguageServerFolderService, , Return Value: "languageServer.0.2.31"
707 2019-03-27T15:58:33.395 INFO (pid:15097) [extension-coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /home/the1900/repo/erp_joyfulworks_api/manage.py
708 2019-03-27T15:58:33.400 INFO (pid:15097) [extension-coc-python] - Python Extension: Interpreters returned by VirtualEnvService are of count 3
709 2019-03-27T15:58:33.405 INFO (pid:15097) [extension-coc-python] - Python Extension: Interpreters returned by CurrentPathService are of count 5
710 2019-03-27T15:58:33.406 INFO (pid:15097) [extension-coc-python] - Python Extension: Cached data exists getEnvironmentVariables, <No Resource>
711 2019-03-27T15:58:33.409 ERROR (pid:15097) [extension-coc-python] - Python Extension: getActivatedEnvironmentVariables TypeError: scriptFile.fileToCommandArgument is not a function
712   ¦ at Bash.<anonymous> (/home/the1900/.config/coc/extensions/node_modules/coc-python/lib/common/terminal/environmentActivationProviders/bash.js:31:42)
713   ¦ at Generator.next (<anonymous>)
714   ¦ at fulfilled (/home/the1900/.config/coc/extensions/node_modules/tslib/tslib.js:104:62)
715 2019-03-27T15:58:33.410 INFO (pid:15097) [extension-coc-python] - Python Extension: getActivatedEnvironmentVariables, Class name = EnvironmentActivationService, Arg 1: <Uri:/home/the1900/repo/erp_joyfulworks_api/manage.py>
716 2019-03-27T15:58:33.410 INFO (pid:15097) [extension-coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /home/the1900/repo/erp_joyfulworks_api/manage.py
717 2019-03-27T15:58:33.411 INFO (pid:15097) [extension-coc-python] - Python Extension: Get language server folder name, Class name = LanguageServerFolderService, , Return Value: "languageServer.0.2.31"
718 2019-03-27T15:58:33.421 ERROR (pid:15097) [server] - uncaughtException Error: spawn /home/the1900/.config/coc/extensions/coc-python-data/languageServer.0.2.31/Microsoft.Python.LanguageServer EACCES
719   ¦ at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
720   ¦ at onErrorNT (internal/child_process.js:415:16)
721   ¦ at process._tickCallback (internal/process/next_tick.js:63:19)
722 2019-03-27T15:58:33.422 ERROR (pid:15097) [server] - unhandledRejection  Promise {
723   <rejected> Error: Launching server using command /home/the1900/.config/coc/extensions/coc-python-data/languageServer.0.2.31/Microsoft.Python.LanguageServer failed.
724   ¦ ¦ at LanguageClient.createMessageTransports (/home/the1900/.local/share/nvim/plugged/coc.nvim/lib/language-client/index.js:343:23) } Error: Launching server using command /home/the1900/.config/coc/extensions/coc-python-data/lang
725   ¦ at LanguageClient.createMessageTransports (/home/the1900/.local/share/nvim/plugged/coc.nvim/lib/language-client/index.js:343:23)
726 2019-03-27T15:58:33.564 INFO (pid:15097) [extension-coc-python] - Python Extension: Interpreters returned by PipEnvService are of count 1
727 2019-03-27T15:58:33.564 INFO (pid:15097) [extension-coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
728 2019-03-27T15:58:33.564 INFO (pid:15097) [extension-coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
729 2019-03-27T15:58:33.564 INFO (pid:15097) [extension-coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
```

**Comment by chemzqm** [comment]
Try `chmod +x /home/the1900/.config/coc/extensions/coc-python-data/languageServer.0.2.31/Microsoft.Python.LanguageServer` in your terminal.

**Comment by the1900** [comment]
Oh is it because of excute permission? I read logs but I coudn't find something related about it. Well I'll try it maybe 12 hours later(at my office) thanks!

**Comment by chemzqm** [comment]
There is chmod operation with that file, but looks like it's failed for some reason.

**Comment by chemzqm** [comment]
Changed to use jedi by default, add `  "python.jediEnabled": false,` to settings file to use MPLS.

**Comment by the1900** [comment]
After I typed what you said. The error is not occurred. But still, there is a problem.

Here is the debug log and as you see It

```
g
304 2019-03-28T10:25:23.596 INFO (pid:5306) [extension-coc-python] - Python Extension: Get language server folder name, Class name = LanguageServerFolderService, , Return Value: "languageServer.0.2.31"
305 2019-03-28T10:25:23.610 DEBUG (pid:5306) [language-client-index] - [python] Error:
306   An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
307   ¦ package: 'runtime.linux-x64.Microsoft.NETCore.App', version: '2.2.2'
308   ¦ path: 'runtimes/linux-x64/lib/netcoreapp2.2/System.Private.DataContractSerialization.dll'
309
310 2019-03-28T10:25:23.625 DEBUG (pid:5306) [language-client-index] - [python] Error:
311   An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
312   ¦ package: 'runtime.linux-x64.Microsoft.NETCore.App', version: '2.2.2'
313   ¦ path: 'runtimes/linux-x64/lib/netcoreapp2.2/System.Private.DataContractSerialization.dll'
314
315 2019-03-28T10:25:23.637 DEBUG (pid:5306) [language-client-index] - [python] Error:
316   An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
317   ¦ package: 'runtime.linux-x64.Microsoft.NETCore.App', version: '2.2.2'
318   ¦ path: 'runtimes/linux-x64/lib/netcoreapp2.2/System.Private.DataContractSerialization.dll'
319
320 2019-03-28T10:25:23.650 DEBUG (pid:5306) [language-client-index] - [python] Error:
321   An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
322   ¦ package: 'runtime.linux-x64.Microsoft.NETCore.App', version: '2.2.2'
323   ¦ path: 'runtimes/linux-x64/lib/netcoreapp2.2/System.Private.DataContractSerialization.dll'
324
325 2019-03-28T10:25:23.662 DEBUG (pid:5306) [language-client-index] - [python] Error:
326   An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
327   ¦ package: 'runtime.linux-x64.Microsoft.NETCore.App', version: '2.2.2'
328   ¦ path: 'runtimes/linux-x64/lib/netcoreapp2.2/System.Private.DataContractSerialization.dll'
329
330 2019-03-28T10:25:23.662 ERROR (pid:5306) [language-client-client] - The python server crashed 5 times in the last 3 minutes. The server will not be restarted.
331 2019-03-28T10:25:24.614 INFO (pid:5306) [extension-coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /home/the1900/.config/coc/extensions/coc-python-data/languageServer.0.2.31/manage.py
332 2019-03-28T10:25:31.684 DEBUG (pid:5306) [events] - Event: BufWinLeave [ 1, 1000 ]
```
I handled it! here is the solution.

when you see the problem with `An assembly specified in the application dependencies manifest something not found` you can just delete `languageServer` directory and in my case the location is `/home/the1900/.config/coc/extensions/coc-python-data/languageServer.0.2.31`. After deleting run vi editor again then it will be redownloaded language server and install it.
